#!/bin/bash
string="$1"
echo "main(t){for(t=0;;t++)putchar($1);}" | gcc -x c - -lm -o /tmp/bytebeat && /tmp/bytebeat | tee >(aplay -r 8000 -) | ffplay -video_size 32x24 -pixel_format gray8a -f rawvideo - 
