#!/bin/bash
S="$1"
(echo "main(t){for(t=0;;t++)putchar($S);}" | gcc -x c - -lm -o /tmp/bytebeat && /tmp/bytebeat | tee /tmp/byte"`date +%m-%d-%H_%M_%S`".dat | tee >(aplay -r 34560 - -c 1) >(mplayer -zoom -x 800 -y 450 -geometry 75%:25% -nosound -nocache -demuxer rawvideo -rawvideo fps=60:w=32:h=18:format=y8 -) > /dev/null)
