#!/bin/bash
S="$1"
(cat "$S" | tee >(aplay -r 34560 - -c 1) >(mplayer -zoom -x 800 -y 450 -geometry 50%:0% -nosound -nocache -demuxer rawvideo -rawvideo fps=60:w=32:h=18:format=y8 -) > /dev/null) && pkill aplay && pkill mplayer
